/*Generated by KISSY Module Compiler*/
KISSY.config('processedModules', {
'biz/page/run': {requires: ['biz/y']},
'biz/y': {requires: ['biz/x','biz/y.css']},
'biz/x': {requires: ['overlay','switchable','biz/x.css']}
});
